defaultProject: readanalytics-qa
defaultLocation: asia-south1
defaultDataset: dataform
defaultAssertionDataset: dataform_assertions
dataformCoreVersion: 3.0.0-beta.4
vars: {
  "batch_id": '',
  "batch_start_ts": '',
  "batch_end_ts": '',
  "assessment_date_list": "''",
  "assessment_month_list": "''",
  "question_topic_id_list": '[]',
  "batch_min_assessment_date": '',
  "batch_max_assessment_date": ''
}
