config {
    type: "assertion",
    tags: ["asserts"],
    dependencies: [
        "df_dimkeys_stg_raft_ar"
    ]
}

SELECT
    perf_score,
    perf_accuracy,
    perf_speed,
    perf_difficulty,
    perf_velocity,
    perf_time_taken
FROM ${ref("df_dimkeys_stg_raft_ar")} 
WHERE
    perf_result <> 'absent' AND (
        perf_score IS NULL OR
        perf_accuracy IS NULL OR
        perf_speed IS NULL OR
        perf_difficulty IS NULL OR
        perf_velocity IS NULL
    )
    OR
    (perf_result <> 'absent' AND perf_result <> 'not_answered' AND perf_time_taken IS NULL)
