config {
  type: "table",
  dependencies: "df_prerpt_sc_rac_day_measures"
}
pre_operations {
    SET @@query_label =
      "step:df_prerpt_sc_rac_day_count_total_assessments, " ||
      "batch_id: ${dataform.projectConfig.vars.batch_id}";
}
SELECT 
    study_circle_id
   , dim_ra_cube_id
   , assessment_date
   , (
        SELECT COUNT(1) FROM UNNEST(arr_assessments)
     ) AS count_total_assessments
FROM readanalytics.df_prerpt_sc_rac_day_measures
